package com.abettaworld.abettaxp.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Experiment.proto

public final class ExperimentOuterClass {
  private ExperimentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExperimentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Experiment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description_control = 3;</code>
     * @return The descriptionControl.
     */
    java.lang.String getDescriptionControl();
    /**
     * <code>string description_control = 3;</code>
     * @return The bytes for descriptionControl.
     */
    com.google.protobuf.ByteString
        getDescriptionControlBytes();

    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    java.util.List<MetricOuterClass.Metric>
        getMetricsControlList();
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    MetricOuterClass.Metric getMetricsControl(int index);
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    int getMetricsControlCount();
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    java.util.List<? extends MetricOuterClass.MetricOrBuilder> 
        getMetricsControlOrBuilderList();
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    MetricOuterClass.MetricOrBuilder getMetricsControlOrBuilder(
        int index);

    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    java.util.List<MetricOuterClass.Metric> 
        getMetricsTreatmentList();
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    MetricOuterClass.Metric getMetricsTreatment(int index);
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    int getMetricsTreatmentCount();
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    java.util.List<? extends MetricOuterClass.MetricOrBuilder> 
        getMetricsTreatmentOrBuilderList();
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    MetricOuterClass.MetricOrBuilder getMetricsTreatmentOrBuilder(
        int index);

    /**
     * <code>.google.protobuf.Timestamp created = 6;</code>
     * @return Whether the created field is set.
     */
    boolean hasCreated();
    /**
     * <code>.google.protobuf.Timestamp created = 6;</code>
     * @return The created.
     */
    com.google.protobuf.Timestamp getCreated();
    /**
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp completed = 7;</code>
     * @return Whether the completed field is set.
     */
    boolean hasCompleted();
    /**
     * <code>.google.protobuf.Timestamp completed = 7;</code>
     * @return The completed.
     */
    com.google.protobuf.Timestamp getCompleted();
    /**
     * <code>.google.protobuf.Timestamp completed = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCompletedOrBuilder();

    /**
     * <code>.Experiment.Status status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.Experiment.Status status = 8;</code>
     * @return The status.
     */
    ExperimentOuterClass.Experiment.Status getStatus();

    /**
     * <code>string description_treatment = 9;</code>
     * @return The descriptionTreatment.
     */
    java.lang.String getDescriptionTreatment();
    /**
     * <code>string description_treatment = 9;</code>
     * @return The bytes for descriptionTreatment.
     */
    com.google.protobuf.ByteString
        getDescriptionTreatmentBytes();

    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    java.util.List<RecommendationOuterClass.Recommendation> 
        getRecommendationsList();
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    RecommendationOuterClass.Recommendation getRecommendations(int index);
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    int getRecommendationsCount();
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    java.util.List<? extends RecommendationOuterClass.RecommendationOrBuilder> 
        getRecommendationsOrBuilderList();
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    RecommendationOuterClass.RecommendationOrBuilder getRecommendationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Experiment}
   */
  public static final class Experiment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Experiment)
      ExperimentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Experiment.newBuilder() to construct.
    private Experiment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Experiment() {
      id_ = "";
      name_ = "";
      descriptionControl_ = "";
      metricsControl_ = java.util.Collections.emptyList();
      metricsTreatment_ = java.util.Collections.emptyList();
      status_ = 0;
      descriptionTreatment_ = "";
      recommendations_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Experiment();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Experiment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              descriptionControl_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                metricsControl_ = new java.util.ArrayList<MetricOuterClass.Metric>();
                mutable_bitField0_ |= 0x00000001;
              }
              metricsControl_.add(
                  input.readMessage(MetricOuterClass.Metric.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                metricsTreatment_ = new java.util.ArrayList<MetricOuterClass.Metric>();
                mutable_bitField0_ |= 0x00000002;
              }
              metricsTreatment_.add(
                  input.readMessage(MetricOuterClass.Metric.parser(), extensionRegistry));
              break;
            }
            case 50: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (created_ != null) {
                subBuilder = created_.toBuilder();
              }
              created_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(created_);
                created_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (completed_ != null) {
                subBuilder = completed_.toBuilder();
              }
              completed_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(completed_);
                completed_ = subBuilder.buildPartial();
              }

              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              descriptionTreatment_ = s;
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                recommendations_ = new java.util.ArrayList<RecommendationOuterClass.Recommendation>();
                mutable_bitField0_ |= 0x00000004;
              }
              recommendations_.add(
                  input.readMessage(RecommendationOuterClass.Recommendation.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          metricsControl_ = java.util.Collections.unmodifiableList(metricsControl_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          metricsTreatment_ = java.util.Collections.unmodifiableList(metricsTreatment_);
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          recommendations_ = java.util.Collections.unmodifiableList(recommendations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExperimentOuterClass.internal_static_Experiment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExperimentOuterClass.internal_static_Experiment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExperimentOuterClass.Experiment.class, ExperimentOuterClass.Experiment.Builder.class);
    }

    /**
     * Protobuf enum {@code Experiment.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOT_STARTED = 0;</code>
       */
      NOT_STARTED(0),
      /**
       * <code>ACTIVE = 1;</code>
       */
      ACTIVE(1),
      /**
       * <code>COMPLETED = 2;</code>
       */
      COMPLETED(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NOT_STARTED = 0;</code>
       */
      public static final int NOT_STARTED_VALUE = 0;
      /**
       * <code>ACTIVE = 1;</code>
       */
      public static final int ACTIVE_VALUE = 1;
      /**
       * <code>COMPLETED = 2;</code>
       */
      public static final int COMPLETED_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return NOT_STARTED;
          case 1: return ACTIVE;
          case 2: return COMPLETED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ExperimentOuterClass.Experiment.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Experiment.Status)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_CONTROL_FIELD_NUMBER = 3;
    private volatile java.lang.Object descriptionControl_;
    /**
     * <code>string description_control = 3;</code>
     * @return The descriptionControl.
     */
    @java.lang.Override
    public java.lang.String getDescriptionControl() {
      java.lang.Object ref = descriptionControl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descriptionControl_ = s;
        return s;
      }
    }
    /**
     * <code>string description_control = 3;</code>
     * @return The bytes for descriptionControl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionControlBytes() {
      java.lang.Object ref = descriptionControl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descriptionControl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METRICS_CONTROL_FIELD_NUMBER = 4;
    private java.util.List<MetricOuterClass.Metric> metricsControl_;
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    @java.lang.Override
    public java.util.List<MetricOuterClass.Metric> getMetricsControlList() {
      return metricsControl_;
    }
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends MetricOuterClass.MetricOrBuilder> 
        getMetricsControlOrBuilderList() {
      return metricsControl_;
    }
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    @java.lang.Override
    public int getMetricsControlCount() {
      return metricsControl_.size();
    }
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    @java.lang.Override
    public MetricOuterClass.Metric getMetricsControl(int index) {
      return metricsControl_.get(index);
    }
    /**
     * <code>repeated .Metric metrics_control = 4;</code>
     */
    @java.lang.Override
    public MetricOuterClass.MetricOrBuilder getMetricsControlOrBuilder(
        int index) {
      return metricsControl_.get(index);
    }

    public static final int METRICS_TREATMENT_FIELD_NUMBER = 5;
    private java.util.List<MetricOuterClass.Metric> metricsTreatment_;
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    @java.lang.Override
    public java.util.List<MetricOuterClass.Metric> getMetricsTreatmentList() {
      return metricsTreatment_;
    }
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends MetricOuterClass.MetricOrBuilder> 
        getMetricsTreatmentOrBuilderList() {
      return metricsTreatment_;
    }
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    @java.lang.Override
    public int getMetricsTreatmentCount() {
      return metricsTreatment_.size();
    }
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    @java.lang.Override
    public MetricOuterClass.Metric getMetricsTreatment(int index) {
      return metricsTreatment_.get(index);
    }
    /**
     * <code>repeated .Metric metrics_treatment = 5;</code>
     */
    @java.lang.Override
    public MetricOuterClass.MetricOrBuilder getMetricsTreatmentOrBuilder(
        int index) {
      return metricsTreatment_.get(index);
    }

    public static final int CREATED_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp created_;
    /**
     * <code>.google.protobuf.Timestamp created = 6;</code>
     * @return Whether the created field is set.
     */
    @java.lang.Override
    public boolean hasCreated() {
      return created_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 6;</code>
     * @return The created.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreated() {
      return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
      return getCreated();
    }

    public static final int COMPLETED_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp completed_;
    /**
     * <code>.google.protobuf.Timestamp completed = 7;</code>
     * @return Whether the completed field is set.
     */
    @java.lang.Override
    public boolean hasCompleted() {
      return completed_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp completed = 7;</code>
     * @return The completed.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCompleted() {
      return completed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completed_;
    }
    /**
     * <code>.google.protobuf.Timestamp completed = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCompletedOrBuilder() {
      return getCompleted();
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>.Experiment.Status status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Experiment.Status status = 8;</code>
     * @return The status.
     */
    @java.lang.Override public ExperimentOuterClass.Experiment.Status getStatus() {
      @SuppressWarnings("deprecation")
      ExperimentOuterClass.Experiment.Status result = ExperimentOuterClass.Experiment.Status.valueOf(status_);
      return result == null ? ExperimentOuterClass.Experiment.Status.UNRECOGNIZED : result;
    }

    public static final int DESCRIPTION_TREATMENT_FIELD_NUMBER = 9;
    private volatile java.lang.Object descriptionTreatment_;
    /**
     * <code>string description_treatment = 9;</code>
     * @return The descriptionTreatment.
     */
    @java.lang.Override
    public java.lang.String getDescriptionTreatment() {
      java.lang.Object ref = descriptionTreatment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descriptionTreatment_ = s;
        return s;
      }
    }
    /**
     * <code>string description_treatment = 9;</code>
     * @return The bytes for descriptionTreatment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionTreatmentBytes() {
      java.lang.Object ref = descriptionTreatment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descriptionTreatment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECOMMENDATIONS_FIELD_NUMBER = 10;
    private java.util.List<RecommendationOuterClass.Recommendation> recommendations_;
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    @java.lang.Override
    public java.util.List<RecommendationOuterClass.Recommendation> getRecommendationsList() {
      return recommendations_;
    }
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    @java.lang.Override
    public java.util.List<? extends RecommendationOuterClass.RecommendationOrBuilder> 
        getRecommendationsOrBuilderList() {
      return recommendations_;
    }
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    @java.lang.Override
    public int getRecommendationsCount() {
      return recommendations_.size();
    }
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    @java.lang.Override
    public RecommendationOuterClass.Recommendation getRecommendations(int index) {
      return recommendations_.get(index);
    }
    /**
     * <code>repeated .Recommendation recommendations = 10;</code>
     */
    @java.lang.Override
    public RecommendationOuterClass.RecommendationOrBuilder getRecommendationsOrBuilder(
        int index) {
      return recommendations_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getDescriptionControlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, descriptionControl_);
      }
      for (int i = 0; i < metricsControl_.size(); i++) {
        output.writeMessage(4, metricsControl_.get(i));
      }
      for (int i = 0; i < metricsTreatment_.size(); i++) {
        output.writeMessage(5, metricsTreatment_.get(i));
      }
      if (created_ != null) {
        output.writeMessage(6, getCreated());
      }
      if (completed_ != null) {
        output.writeMessage(7, getCompleted());
      }
      if (status_ != ExperimentOuterClass.Experiment.Status.NOT_STARTED.getNumber()) {
        output.writeEnum(8, status_);
      }
      if (!getDescriptionTreatmentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, descriptionTreatment_);
      }
      for (int i = 0; i < recommendations_.size(); i++) {
        output.writeMessage(10, recommendations_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getDescriptionControlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, descriptionControl_);
      }
      for (int i = 0; i < metricsControl_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, metricsControl_.get(i));
      }
      for (int i = 0; i < metricsTreatment_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, metricsTreatment_.get(i));
      }
      if (created_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getCreated());
      }
      if (completed_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getCompleted());
      }
      if (status_ != ExperimentOuterClass.Experiment.Status.NOT_STARTED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, status_);
      }
      if (!getDescriptionTreatmentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, descriptionTreatment_);
      }
      for (int i = 0; i < recommendations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, recommendations_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ExperimentOuterClass.Experiment)) {
        return super.equals(obj);
      }
      ExperimentOuterClass.Experiment other = (ExperimentOuterClass.Experiment) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescriptionControl()
          .equals(other.getDescriptionControl())) return false;
      if (!getMetricsControlList()
          .equals(other.getMetricsControlList())) return false;
      if (!getMetricsTreatmentList()
          .equals(other.getMetricsTreatmentList())) return false;
      if (hasCreated() != other.hasCreated()) return false;
      if (hasCreated()) {
        if (!getCreated()
            .equals(other.getCreated())) return false;
      }
      if (hasCompleted() != other.hasCompleted()) return false;
      if (hasCompleted()) {
        if (!getCompleted()
            .equals(other.getCompleted())) return false;
      }
      if (status_ != other.status_) return false;
      if (!getDescriptionTreatment()
          .equals(other.getDescriptionTreatment())) return false;
      if (!getRecommendationsList()
          .equals(other.getRecommendationsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_CONTROL_FIELD_NUMBER;
      hash = (53 * hash) + getDescriptionControl().hashCode();
      if (getMetricsControlCount() > 0) {
        hash = (37 * hash) + METRICS_CONTROL_FIELD_NUMBER;
        hash = (53 * hash) + getMetricsControlList().hashCode();
      }
      if (getMetricsTreatmentCount() > 0) {
        hash = (37 * hash) + METRICS_TREATMENT_FIELD_NUMBER;
        hash = (53 * hash) + getMetricsTreatmentList().hashCode();
      }
      if (hasCreated()) {
        hash = (37 * hash) + CREATED_FIELD_NUMBER;
        hash = (53 * hash) + getCreated().hashCode();
      }
      if (hasCompleted()) {
        hash = (37 * hash) + COMPLETED_FIELD_NUMBER;
        hash = (53 * hash) + getCompleted().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + DESCRIPTION_TREATMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDescriptionTreatment().hashCode();
      if (getRecommendationsCount() > 0) {
        hash = (37 * hash) + RECOMMENDATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getRecommendationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ExperimentOuterClass.Experiment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExperimentOuterClass.Experiment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExperimentOuterClass.Experiment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExperimentOuterClass.Experiment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExperimentOuterClass.Experiment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExperimentOuterClass.Experiment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExperimentOuterClass.Experiment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExperimentOuterClass.Experiment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExperimentOuterClass.Experiment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ExperimentOuterClass.Experiment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExperimentOuterClass.Experiment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExperimentOuterClass.Experiment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ExperimentOuterClass.Experiment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Experiment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Experiment)
        ExperimentOuterClass.ExperimentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExperimentOuterClass.internal_static_Experiment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExperimentOuterClass.internal_static_Experiment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ExperimentOuterClass.Experiment.class, ExperimentOuterClass.Experiment.Builder.class);
      }

      // Construct using ExperimentOuterClass.Experiment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMetricsControlFieldBuilder();
          getMetricsTreatmentFieldBuilder();
          getRecommendationsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        descriptionControl_ = "";

        if (metricsControlBuilder_ == null) {
          metricsControl_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          metricsControlBuilder_.clear();
        }
        if (metricsTreatmentBuilder_ == null) {
          metricsTreatment_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          metricsTreatmentBuilder_.clear();
        }
        if (createdBuilder_ == null) {
          created_ = null;
        } else {
          created_ = null;
          createdBuilder_ = null;
        }
        if (completedBuilder_ == null) {
          completed_ = null;
        } else {
          completed_ = null;
          completedBuilder_ = null;
        }
        status_ = 0;

        descriptionTreatment_ = "";

        if (recommendationsBuilder_ == null) {
          recommendations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          recommendationsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExperimentOuterClass.internal_static_Experiment_descriptor;
      }

      @java.lang.Override
      public ExperimentOuterClass.Experiment getDefaultInstanceForType() {
        return ExperimentOuterClass.Experiment.getDefaultInstance();
      }

      @java.lang.Override
      public ExperimentOuterClass.Experiment build() {
        ExperimentOuterClass.Experiment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ExperimentOuterClass.Experiment buildPartial() {
        ExperimentOuterClass.Experiment result = new ExperimentOuterClass.Experiment(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.descriptionControl_ = descriptionControl_;
        if (metricsControlBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            metricsControl_ = java.util.Collections.unmodifiableList(metricsControl_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.metricsControl_ = metricsControl_;
        } else {
          result.metricsControl_ = metricsControlBuilder_.build();
        }
        if (metricsTreatmentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            metricsTreatment_ = java.util.Collections.unmodifiableList(metricsTreatment_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.metricsTreatment_ = metricsTreatment_;
        } else {
          result.metricsTreatment_ = metricsTreatmentBuilder_.build();
        }
        if (createdBuilder_ == null) {
          result.created_ = created_;
        } else {
          result.created_ = createdBuilder_.build();
        }
        if (completedBuilder_ == null) {
          result.completed_ = completed_;
        } else {
          result.completed_ = completedBuilder_.build();
        }
        result.status_ = status_;
        result.descriptionTreatment_ = descriptionTreatment_;
        if (recommendationsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            recommendations_ = java.util.Collections.unmodifiableList(recommendations_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.recommendations_ = recommendations_;
        } else {
          result.recommendations_ = recommendationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ExperimentOuterClass.Experiment) {
          return mergeFrom((ExperimentOuterClass.Experiment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ExperimentOuterClass.Experiment other) {
        if (other == ExperimentOuterClass.Experiment.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescriptionControl().isEmpty()) {
          descriptionControl_ = other.descriptionControl_;
          onChanged();
        }
        if (metricsControlBuilder_ == null) {
          if (!other.metricsControl_.isEmpty()) {
            if (metricsControl_.isEmpty()) {
              metricsControl_ = other.metricsControl_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMetricsControlIsMutable();
              metricsControl_.addAll(other.metricsControl_);
            }
            onChanged();
          }
        } else {
          if (!other.metricsControl_.isEmpty()) {
            if (metricsControlBuilder_.isEmpty()) {
              metricsControlBuilder_.dispose();
              metricsControlBuilder_ = null;
              metricsControl_ = other.metricsControl_;
              bitField0_ = (bitField0_ & ~0x00000001);
              metricsControlBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMetricsControlFieldBuilder() : null;
            } else {
              metricsControlBuilder_.addAllMessages(other.metricsControl_);
            }
          }
        }
        if (metricsTreatmentBuilder_ == null) {
          if (!other.metricsTreatment_.isEmpty()) {
            if (metricsTreatment_.isEmpty()) {
              metricsTreatment_ = other.metricsTreatment_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMetricsTreatmentIsMutable();
              metricsTreatment_.addAll(other.metricsTreatment_);
            }
            onChanged();
          }
        } else {
          if (!other.metricsTreatment_.isEmpty()) {
            if (metricsTreatmentBuilder_.isEmpty()) {
              metricsTreatmentBuilder_.dispose();
              metricsTreatmentBuilder_ = null;
              metricsTreatment_ = other.metricsTreatment_;
              bitField0_ = (bitField0_ & ~0x00000002);
              metricsTreatmentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMetricsTreatmentFieldBuilder() : null;
            } else {
              metricsTreatmentBuilder_.addAllMessages(other.metricsTreatment_);
            }
          }
        }
        if (other.hasCreated()) {
          mergeCreated(other.getCreated());
        }
        if (other.hasCompleted()) {
          mergeCompleted(other.getCompleted());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getDescriptionTreatment().isEmpty()) {
          descriptionTreatment_ = other.descriptionTreatment_;
          onChanged();
        }
        if (recommendationsBuilder_ == null) {
          if (!other.recommendations_.isEmpty()) {
            if (recommendations_.isEmpty()) {
              recommendations_ = other.recommendations_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRecommendationsIsMutable();
              recommendations_.addAll(other.recommendations_);
            }
            onChanged();
          }
        } else {
          if (!other.recommendations_.isEmpty()) {
            if (recommendationsBuilder_.isEmpty()) {
              recommendationsBuilder_.dispose();
              recommendationsBuilder_ = null;
              recommendations_ = other.recommendations_;
              bitField0_ = (bitField0_ & ~0x00000004);
              recommendationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecommendationsFieldBuilder() : null;
            } else {
              recommendationsBuilder_.addAllMessages(other.recommendations_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ExperimentOuterClass.Experiment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ExperimentOuterClass.Experiment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object descriptionControl_ = "";
      /**
       * <code>string description_control = 3;</code>
       * @return The descriptionControl.
       */
      public java.lang.String getDescriptionControl() {
        java.lang.Object ref = descriptionControl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          descriptionControl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description_control = 3;</code>
       * @return The bytes for descriptionControl.
       */
      public com.google.protobuf.ByteString
          getDescriptionControlBytes() {
        java.lang.Object ref = descriptionControl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          descriptionControl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description_control = 3;</code>
       * @param value The descriptionControl to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionControl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        descriptionControl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description_control = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescriptionControl() {
        
        descriptionControl_ = getDefaultInstance().getDescriptionControl();
        onChanged();
        return this;
      }
      /**
       * <code>string description_control = 3;</code>
       * @param value The bytes for descriptionControl to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionControlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        descriptionControl_ = value;
        onChanged();
        return this;
      }

      private java.util.List<MetricOuterClass.Metric> metricsControl_ =
        java.util.Collections.emptyList();
      private void ensureMetricsControlIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          metricsControl_ = new java.util.ArrayList<MetricOuterClass.Metric>(metricsControl_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder> metricsControlBuilder_;

      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public java.util.List<MetricOuterClass.Metric> getMetricsControlList() {
        if (metricsControlBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metricsControl_);
        } else {
          return metricsControlBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public int getMetricsControlCount() {
        if (metricsControlBuilder_ == null) {
          return metricsControl_.size();
        } else {
          return metricsControlBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public MetricOuterClass.Metric getMetricsControl(int index) {
        if (metricsControlBuilder_ == null) {
          return metricsControl_.get(index);
        } else {
          return metricsControlBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder setMetricsControl(
          int index, MetricOuterClass.Metric value) {
        if (metricsControlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsControlIsMutable();
          metricsControl_.set(index, value);
          onChanged();
        } else {
          metricsControlBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder setMetricsControl(
          int index, MetricOuterClass.Metric.Builder builderForValue) {
        if (metricsControlBuilder_ == null) {
          ensureMetricsControlIsMutable();
          metricsControl_.set(index, builderForValue.build());
          onChanged();
        } else {
          metricsControlBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder addMetricsControl(MetricOuterClass.Metric value) {
        if (metricsControlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsControlIsMutable();
          metricsControl_.add(value);
          onChanged();
        } else {
          metricsControlBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder addMetricsControl(
          int index, MetricOuterClass.Metric value) {
        if (metricsControlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsControlIsMutable();
          metricsControl_.add(index, value);
          onChanged();
        } else {
          metricsControlBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder addMetricsControl(
          MetricOuterClass.Metric.Builder builderForValue) {
        if (metricsControlBuilder_ == null) {
          ensureMetricsControlIsMutable();
          metricsControl_.add(builderForValue.build());
          onChanged();
        } else {
          metricsControlBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder addMetricsControl(
          int index, MetricOuterClass.Metric.Builder builderForValue) {
        if (metricsControlBuilder_ == null) {
          ensureMetricsControlIsMutable();
          metricsControl_.add(index, builderForValue.build());
          onChanged();
        } else {
          metricsControlBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder addAllMetricsControl(
          java.lang.Iterable<? extends MetricOuterClass.Metric> values) {
        if (metricsControlBuilder_ == null) {
          ensureMetricsControlIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, metricsControl_);
          onChanged();
        } else {
          metricsControlBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder clearMetricsControl() {
        if (metricsControlBuilder_ == null) {
          metricsControl_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          metricsControlBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public Builder removeMetricsControl(int index) {
        if (metricsControlBuilder_ == null) {
          ensureMetricsControlIsMutable();
          metricsControl_.remove(index);
          onChanged();
        } else {
          metricsControlBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public MetricOuterClass.Metric.Builder getMetricsControlBuilder(
          int index) {
        return getMetricsControlFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public MetricOuterClass.MetricOrBuilder getMetricsControlOrBuilder(
          int index) {
        if (metricsControlBuilder_ == null) {
          return metricsControl_.get(index);  } else {
          return metricsControlBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public java.util.List<? extends MetricOuterClass.MetricOrBuilder> 
           getMetricsControlOrBuilderList() {
        if (metricsControlBuilder_ != null) {
          return metricsControlBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metricsControl_);
        }
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public MetricOuterClass.Metric.Builder addMetricsControlBuilder() {
        return getMetricsControlFieldBuilder().addBuilder(
            MetricOuterClass.Metric.getDefaultInstance());
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public MetricOuterClass.Metric.Builder addMetricsControlBuilder(
          int index) {
        return getMetricsControlFieldBuilder().addBuilder(
            index, MetricOuterClass.Metric.getDefaultInstance());
      }
      /**
       * <code>repeated .Metric metrics_control = 4;</code>
       */
      public java.util.List<MetricOuterClass.Metric.Builder> 
           getMetricsControlBuilderList() {
        return getMetricsControlFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder> 
          getMetricsControlFieldBuilder() {
        if (metricsControlBuilder_ == null) {
          metricsControlBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder>(
                  metricsControl_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          metricsControl_ = null;
        }
        return metricsControlBuilder_;
      }

      private java.util.List<MetricOuterClass.Metric> metricsTreatment_ =
        java.util.Collections.emptyList();
      private void ensureMetricsTreatmentIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          metricsTreatment_ = new java.util.ArrayList<MetricOuterClass.Metric>(metricsTreatment_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder> metricsTreatmentBuilder_;

      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public java.util.List<MetricOuterClass.Metric> getMetricsTreatmentList() {
        if (metricsTreatmentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metricsTreatment_);
        } else {
          return metricsTreatmentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public int getMetricsTreatmentCount() {
        if (metricsTreatmentBuilder_ == null) {
          return metricsTreatment_.size();
        } else {
          return metricsTreatmentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public MetricOuterClass.Metric getMetricsTreatment(int index) {
        if (metricsTreatmentBuilder_ == null) {
          return metricsTreatment_.get(index);
        } else {
          return metricsTreatmentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder setMetricsTreatment(
          int index, MetricOuterClass.Metric value) {
        if (metricsTreatmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsTreatmentIsMutable();
          metricsTreatment_.set(index, value);
          onChanged();
        } else {
          metricsTreatmentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder setMetricsTreatment(
          int index, MetricOuterClass.Metric.Builder builderForValue) {
        if (metricsTreatmentBuilder_ == null) {
          ensureMetricsTreatmentIsMutable();
          metricsTreatment_.set(index, builderForValue.build());
          onChanged();
        } else {
          metricsTreatmentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder addMetricsTreatment(MetricOuterClass.Metric value) {
        if (metricsTreatmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsTreatmentIsMutable();
          metricsTreatment_.add(value);
          onChanged();
        } else {
          metricsTreatmentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder addMetricsTreatment(
          int index, MetricOuterClass.Metric value) {
        if (metricsTreatmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsTreatmentIsMutable();
          metricsTreatment_.add(index, value);
          onChanged();
        } else {
          metricsTreatmentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder addMetricsTreatment(
          MetricOuterClass.Metric.Builder builderForValue) {
        if (metricsTreatmentBuilder_ == null) {
          ensureMetricsTreatmentIsMutable();
          metricsTreatment_.add(builderForValue.build());
          onChanged();
        } else {
          metricsTreatmentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder addMetricsTreatment(
          int index, MetricOuterClass.Metric.Builder builderForValue) {
        if (metricsTreatmentBuilder_ == null) {
          ensureMetricsTreatmentIsMutable();
          metricsTreatment_.add(index, builderForValue.build());
          onChanged();
        } else {
          metricsTreatmentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder addAllMetricsTreatment(
          java.lang.Iterable<? extends MetricOuterClass.Metric> values) {
        if (metricsTreatmentBuilder_ == null) {
          ensureMetricsTreatmentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, metricsTreatment_);
          onChanged();
        } else {
          metricsTreatmentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder clearMetricsTreatment() {
        if (metricsTreatmentBuilder_ == null) {
          metricsTreatment_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          metricsTreatmentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public Builder removeMetricsTreatment(int index) {
        if (metricsTreatmentBuilder_ == null) {
          ensureMetricsTreatmentIsMutable();
          metricsTreatment_.remove(index);
          onChanged();
        } else {
          metricsTreatmentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public MetricOuterClass.Metric.Builder getMetricsTreatmentBuilder(
          int index) {
        return getMetricsTreatmentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public MetricOuterClass.MetricOrBuilder getMetricsTreatmentOrBuilder(
          int index) {
        if (metricsTreatmentBuilder_ == null) {
          return metricsTreatment_.get(index);  } else {
          return metricsTreatmentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public java.util.List<? extends MetricOuterClass.MetricOrBuilder> 
           getMetricsTreatmentOrBuilderList() {
        if (metricsTreatmentBuilder_ != null) {
          return metricsTreatmentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metricsTreatment_);
        }
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public MetricOuterClass.Metric.Builder addMetricsTreatmentBuilder() {
        return getMetricsTreatmentFieldBuilder().addBuilder(
            MetricOuterClass.Metric.getDefaultInstance());
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public MetricOuterClass.Metric.Builder addMetricsTreatmentBuilder(
          int index) {
        return getMetricsTreatmentFieldBuilder().addBuilder(
            index, MetricOuterClass.Metric.getDefaultInstance());
      }
      /**
       * <code>repeated .Metric metrics_treatment = 5;</code>
       */
      public java.util.List<MetricOuterClass.Metric.Builder> 
           getMetricsTreatmentBuilderList() {
        return getMetricsTreatmentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder> 
          getMetricsTreatmentFieldBuilder() {
        if (metricsTreatmentBuilder_ == null) {
          metricsTreatmentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder>(
                  metricsTreatment_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          metricsTreatment_ = null;
        }
        return metricsTreatmentBuilder_;
      }

      private com.google.protobuf.Timestamp created_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdBuilder_;
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       * @return Whether the created field is set.
       */
      public boolean hasCreated() {
        return createdBuilder_ != null || created_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       * @return The created.
       */
      public com.google.protobuf.Timestamp getCreated() {
        if (createdBuilder_ == null) {
          return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
        } else {
          return createdBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       */
      public Builder setCreated(com.google.protobuf.Timestamp value) {
        if (createdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          created_ = value;
          onChanged();
        } else {
          createdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       */
      public Builder setCreated(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdBuilder_ == null) {
          created_ = builderForValue.build();
          onChanged();
        } else {
          createdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       */
      public Builder mergeCreated(com.google.protobuf.Timestamp value) {
        if (createdBuilder_ == null) {
          if (created_ != null) {
            created_ =
              com.google.protobuf.Timestamp.newBuilder(created_).mergeFrom(value).buildPartial();
          } else {
            created_ = value;
          }
          onChanged();
        } else {
          createdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       */
      public Builder clearCreated() {
        if (createdBuilder_ == null) {
          created_ = null;
          onChanged();
        } else {
          created_ = null;
          createdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedBuilder() {
        
        onChanged();
        return getCreatedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
        if (createdBuilder_ != null) {
          return createdBuilder_.getMessageOrBuilder();
        } else {
          return created_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : created_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreatedFieldBuilder() {
        if (createdBuilder_ == null) {
          createdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreated(),
                  getParentForChildren(),
                  isClean());
          created_ = null;
        }
        return createdBuilder_;
      }

      private com.google.protobuf.Timestamp completed_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> completedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       * @return Whether the completed field is set.
       */
      public boolean hasCompleted() {
        return completedBuilder_ != null || completed_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       * @return The completed.
       */
      public com.google.protobuf.Timestamp getCompleted() {
        if (completedBuilder_ == null) {
          return completed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completed_;
        } else {
          return completedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       */
      public Builder setCompleted(com.google.protobuf.Timestamp value) {
        if (completedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          completed_ = value;
          onChanged();
        } else {
          completedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       */
      public Builder setCompleted(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (completedBuilder_ == null) {
          completed_ = builderForValue.build();
          onChanged();
        } else {
          completedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       */
      public Builder mergeCompleted(com.google.protobuf.Timestamp value) {
        if (completedBuilder_ == null) {
          if (completed_ != null) {
            completed_ =
              com.google.protobuf.Timestamp.newBuilder(completed_).mergeFrom(value).buildPartial();
          } else {
            completed_ = value;
          }
          onChanged();
        } else {
          completedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       */
      public Builder clearCompleted() {
        if (completedBuilder_ == null) {
          completed_ = null;
          onChanged();
        } else {
          completed_ = null;
          completedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCompletedBuilder() {
        
        onChanged();
        return getCompletedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCompletedOrBuilder() {
        if (completedBuilder_ != null) {
          return completedBuilder_.getMessageOrBuilder();
        } else {
          return completed_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : completed_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp completed = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCompletedFieldBuilder() {
        if (completedBuilder_ == null) {
          completedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCompleted(),
                  getParentForChildren(),
                  isClean());
          completed_ = null;
        }
        return completedBuilder_;
      }

      private int status_ = 0;
      /**
       * <code>.Experiment.Status status = 8;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.Experiment.Status status = 8;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Experiment.Status status = 8;</code>
       * @return The status.
       */
      @java.lang.Override
      public ExperimentOuterClass.Experiment.Status getStatus() {
        @SuppressWarnings("deprecation")
        ExperimentOuterClass.Experiment.Status result = ExperimentOuterClass.Experiment.Status.valueOf(status_);
        return result == null ? ExperimentOuterClass.Experiment.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.Experiment.Status status = 8;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(ExperimentOuterClass.Experiment.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Experiment.Status status = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object descriptionTreatment_ = "";
      /**
       * <code>string description_treatment = 9;</code>
       * @return The descriptionTreatment.
       */
      public java.lang.String getDescriptionTreatment() {
        java.lang.Object ref = descriptionTreatment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          descriptionTreatment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description_treatment = 9;</code>
       * @return The bytes for descriptionTreatment.
       */
      public com.google.protobuf.ByteString
          getDescriptionTreatmentBytes() {
        java.lang.Object ref = descriptionTreatment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          descriptionTreatment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description_treatment = 9;</code>
       * @param value The descriptionTreatment to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionTreatment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        descriptionTreatment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description_treatment = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescriptionTreatment() {
        
        descriptionTreatment_ = getDefaultInstance().getDescriptionTreatment();
        onChanged();
        return this;
      }
      /**
       * <code>string description_treatment = 9;</code>
       * @param value The bytes for descriptionTreatment to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionTreatmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        descriptionTreatment_ = value;
        onChanged();
        return this;
      }

      private java.util.List<RecommendationOuterClass.Recommendation> recommendations_ =
        java.util.Collections.emptyList();
      private void ensureRecommendationsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          recommendations_ = new java.util.ArrayList<RecommendationOuterClass.Recommendation>(recommendations_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          RecommendationOuterClass.Recommendation, RecommendationOuterClass.Recommendation.Builder, RecommendationOuterClass.RecommendationOrBuilder> recommendationsBuilder_;

      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public java.util.List<RecommendationOuterClass.Recommendation> getRecommendationsList() {
        if (recommendationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recommendations_);
        } else {
          return recommendationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public int getRecommendationsCount() {
        if (recommendationsBuilder_ == null) {
          return recommendations_.size();
        } else {
          return recommendationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public RecommendationOuterClass.Recommendation getRecommendations(int index) {
        if (recommendationsBuilder_ == null) {
          return recommendations_.get(index);
        } else {
          return recommendationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder setRecommendations(
          int index, RecommendationOuterClass.Recommendation value) {
        if (recommendationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecommendationsIsMutable();
          recommendations_.set(index, value);
          onChanged();
        } else {
          recommendationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder setRecommendations(
          int index, RecommendationOuterClass.Recommendation.Builder builderForValue) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          recommendations_.set(index, builderForValue.build());
          onChanged();
        } else {
          recommendationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder addRecommendations(RecommendationOuterClass.Recommendation value) {
        if (recommendationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecommendationsIsMutable();
          recommendations_.add(value);
          onChanged();
        } else {
          recommendationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder addRecommendations(
          int index, RecommendationOuterClass.Recommendation value) {
        if (recommendationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecommendationsIsMutable();
          recommendations_.add(index, value);
          onChanged();
        } else {
          recommendationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder addRecommendations(
          RecommendationOuterClass.Recommendation.Builder builderForValue) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          recommendations_.add(builderForValue.build());
          onChanged();
        } else {
          recommendationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder addRecommendations(
          int index, RecommendationOuterClass.Recommendation.Builder builderForValue) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          recommendations_.add(index, builderForValue.build());
          onChanged();
        } else {
          recommendationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder addAllRecommendations(
          java.lang.Iterable<? extends RecommendationOuterClass.Recommendation> values) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, recommendations_);
          onChanged();
        } else {
          recommendationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder clearRecommendations() {
        if (recommendationsBuilder_ == null) {
          recommendations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          recommendationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public Builder removeRecommendations(int index) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          recommendations_.remove(index);
          onChanged();
        } else {
          recommendationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public RecommendationOuterClass.Recommendation.Builder getRecommendationsBuilder(
          int index) {
        return getRecommendationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public RecommendationOuterClass.RecommendationOrBuilder getRecommendationsOrBuilder(
          int index) {
        if (recommendationsBuilder_ == null) {
          return recommendations_.get(index);  } else {
          return recommendationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public java.util.List<? extends RecommendationOuterClass.RecommendationOrBuilder> 
           getRecommendationsOrBuilderList() {
        if (recommendationsBuilder_ != null) {
          return recommendationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recommendations_);
        }
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public RecommendationOuterClass.Recommendation.Builder addRecommendationsBuilder() {
        return getRecommendationsFieldBuilder().addBuilder(
            RecommendationOuterClass.Recommendation.getDefaultInstance());
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public RecommendationOuterClass.Recommendation.Builder addRecommendationsBuilder(
          int index) {
        return getRecommendationsFieldBuilder().addBuilder(
            index, RecommendationOuterClass.Recommendation.getDefaultInstance());
      }
      /**
       * <code>repeated .Recommendation recommendations = 10;</code>
       */
      public java.util.List<RecommendationOuterClass.Recommendation.Builder> 
           getRecommendationsBuilderList() {
        return getRecommendationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          RecommendationOuterClass.Recommendation, RecommendationOuterClass.Recommendation.Builder, RecommendationOuterClass.RecommendationOrBuilder> 
          getRecommendationsFieldBuilder() {
        if (recommendationsBuilder_ == null) {
          recommendationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              RecommendationOuterClass.Recommendation, RecommendationOuterClass.Recommendation.Builder, RecommendationOuterClass.RecommendationOrBuilder>(
                  recommendations_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          recommendations_ = null;
        }
        return recommendationsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Experiment)
    }

    // @@protoc_insertion_point(class_scope:Experiment)
    private static final ExperimentOuterClass.Experiment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ExperimentOuterClass.Experiment();
    }

    public static ExperimentOuterClass.Experiment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Experiment>
        PARSER = new com.google.protobuf.AbstractParser<Experiment>() {
      @java.lang.Override
      public Experiment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Experiment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Experiment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Experiment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ExperimentOuterClass.Experiment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Experiment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Experiment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Experiment.proto\032\037google/protobuf/time" +
      "stamp.proto\032\014Metric.proto\032\024Recommendatio" +
      "n.proto\"\210\003\n\nExperiment\022\n\n\002id\030\001 \001(\t\022\014\n\004na" +
      "me\030\002 \001(\t\022\033\n\023description_control\030\003 \001(\t\022 \n" +
      "\017metrics_control\030\004 \003(\0132\007.Metric\022\"\n\021metri" +
      "cs_treatment\030\005 \003(\0132\007.Metric\022+\n\007created\030\006" +
      " \001(\0132\032.google.protobuf.Timestamp\022-\n\tcomp" +
      "leted\030\007 \001(\0132\032.google.protobuf.Timestamp\022" +
      "\"\n\006status\030\010 \001(\0162\022.Experiment.Status\022\035\n\025d" +
      "escription_treatment\030\t \001(\t\022(\n\017recommenda" +
      "tions\030\n \003(\0132\017.Recommendation\"4\n\006Status\022\017" +
      "\n\013NOT_STARTED\020\000\022\n\n\006ACTIVE\020\001\022\r\n\tCOMPLETED" +
      "\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          MetricOuterClass.getDescriptor(),
          RecommendationOuterClass.getDescriptor(),
        });
    internal_static_Experiment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Experiment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Experiment_descriptor,
        new java.lang.String[] { "Id", "Name", "DescriptionControl", "MetricsControl", "MetricsTreatment", "Created", "Completed", "Status", "DescriptionTreatment", "Recommendations", });
    com.google.protobuf.TimestampProto.getDescriptor();
    MetricOuterClass.getDescriptor();
    RecommendationOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
