package com.abettaworld.abettaxp.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Recommendation.proto

public final class RecommendationOuterClass {
  private RecommendationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecommendationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Recommendation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.Metric metric_control = 2;</code>
     * @return Whether the metricControl field is set.
     */
    boolean hasMetricControl();
    /**
     * <code>.Metric metric_control = 2;</code>
     * @return The metricControl.
     */
    MetricOuterClass.Metric getMetricControl();
    /**
     * <code>.Metric metric_control = 2;</code>
     */
    MetricOuterClass.MetricOrBuilder getMetricControlOrBuilder();

    /**
     * <code>.Metric metric_treatment = 3;</code>
     * @return Whether the metricTreatment field is set.
     */
    boolean hasMetricTreatment();
    /**
     * <code>.Metric metric_treatment = 3;</code>
     * @return The metricTreatment.
     */
    MetricOuterClass.Metric getMetricTreatment();
    /**
     * <code>.Metric metric_treatment = 3;</code>
     */
    MetricOuterClass.MetricOrBuilder getMetricTreatmentOrBuilder();

    /**
     * <code>double avg_control = 4;</code>
     * @return The avgControl.
     */
    double getAvgControl();

    /**
     * <code>double avg_treatment = 5;</code>
     * @return The avgTreatment.
     */
    double getAvgTreatment();

    /**
     * <code>double p_value = 6;</code>
     * @return The pValue.
     */
    double getPValue();
  }
  /**
   * Protobuf type {@code Recommendation}
   */
  public static final class Recommendation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Recommendation)
      RecommendationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Recommendation.newBuilder() to construct.
    private Recommendation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Recommendation() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Recommendation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Recommendation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              MetricOuterClass.Metric.Builder subBuilder = null;
              if (metricControl_ != null) {
                subBuilder = metricControl_.toBuilder();
              }
              metricControl_ = input.readMessage(MetricOuterClass.Metric.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metricControl_);
                metricControl_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              MetricOuterClass.Metric.Builder subBuilder = null;
              if (metricTreatment_ != null) {
                subBuilder = metricTreatment_.toBuilder();
              }
              metricTreatment_ = input.readMessage(MetricOuterClass.Metric.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metricTreatment_);
                metricTreatment_ = subBuilder.buildPartial();
              }

              break;
            }
            case 33: {

              avgControl_ = input.readDouble();
              break;
            }
            case 41: {

              avgTreatment_ = input.readDouble();
              break;
            }
            case 49: {

              pValue_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecommendationOuterClass.internal_static_Recommendation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecommendationOuterClass.internal_static_Recommendation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecommendationOuterClass.Recommendation.class, RecommendationOuterClass.Recommendation.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METRIC_CONTROL_FIELD_NUMBER = 2;
    private MetricOuterClass.Metric metricControl_;
    /**
     * <code>.Metric metric_control = 2;</code>
     * @return Whether the metricControl field is set.
     */
    @java.lang.Override
    public boolean hasMetricControl() {
      return metricControl_ != null;
    }
    /**
     * <code>.Metric metric_control = 2;</code>
     * @return The metricControl.
     */
    @java.lang.Override
    public MetricOuterClass.Metric getMetricControl() {
      return metricControl_ == null ? MetricOuterClass.Metric.getDefaultInstance() : metricControl_;
    }
    /**
     * <code>.Metric metric_control = 2;</code>
     */
    @java.lang.Override
    public MetricOuterClass.MetricOrBuilder getMetricControlOrBuilder() {
      return getMetricControl();
    }

    public static final int METRIC_TREATMENT_FIELD_NUMBER = 3;
    private MetricOuterClass.Metric metricTreatment_;
    /**
     * <code>.Metric metric_treatment = 3;</code>
     * @return Whether the metricTreatment field is set.
     */
    @java.lang.Override
    public boolean hasMetricTreatment() {
      return metricTreatment_ != null;
    }
    /**
     * <code>.Metric metric_treatment = 3;</code>
     * @return The metricTreatment.
     */
    @java.lang.Override
    public MetricOuterClass.Metric getMetricTreatment() {
      return metricTreatment_ == null ? MetricOuterClass.Metric.getDefaultInstance() : metricTreatment_;
    }
    /**
     * <code>.Metric metric_treatment = 3;</code>
     */
    @java.lang.Override
    public MetricOuterClass.MetricOrBuilder getMetricTreatmentOrBuilder() {
      return getMetricTreatment();
    }

    public static final int AVG_CONTROL_FIELD_NUMBER = 4;
    private double avgControl_;
    /**
     * <code>double avg_control = 4;</code>
     * @return The avgControl.
     */
    @java.lang.Override
    public double getAvgControl() {
      return avgControl_;
    }

    public static final int AVG_TREATMENT_FIELD_NUMBER = 5;
    private double avgTreatment_;
    /**
     * <code>double avg_treatment = 5;</code>
     * @return The avgTreatment.
     */
    @java.lang.Override
    public double getAvgTreatment() {
      return avgTreatment_;
    }

    public static final int P_VALUE_FIELD_NUMBER = 6;
    private double pValue_;
    /**
     * <code>double p_value = 6;</code>
     * @return The pValue.
     */
    @java.lang.Override
    public double getPValue() {
      return pValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (metricControl_ != null) {
        output.writeMessage(2, getMetricControl());
      }
      if (metricTreatment_ != null) {
        output.writeMessage(3, getMetricTreatment());
      }
      if (avgControl_ != 0D) {
        output.writeDouble(4, avgControl_);
      }
      if (avgTreatment_ != 0D) {
        output.writeDouble(5, avgTreatment_);
      }
      if (pValue_ != 0D) {
        output.writeDouble(6, pValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (metricControl_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMetricControl());
      }
      if (metricTreatment_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMetricTreatment());
      }
      if (avgControl_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, avgControl_);
      }
      if (avgTreatment_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, avgTreatment_);
      }
      if (pValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, pValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RecommendationOuterClass.Recommendation)) {
        return super.equals(obj);
      }
      RecommendationOuterClass.Recommendation other = (RecommendationOuterClass.Recommendation) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (hasMetricControl() != other.hasMetricControl()) return false;
      if (hasMetricControl()) {
        if (!getMetricControl()
            .equals(other.getMetricControl())) return false;
      }
      if (hasMetricTreatment() != other.hasMetricTreatment()) return false;
      if (hasMetricTreatment()) {
        if (!getMetricTreatment()
            .equals(other.getMetricTreatment())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getAvgControl())
          != java.lang.Double.doubleToLongBits(
              other.getAvgControl())) return false;
      if (java.lang.Double.doubleToLongBits(getAvgTreatment())
          != java.lang.Double.doubleToLongBits(
              other.getAvgTreatment())) return false;
      if (java.lang.Double.doubleToLongBits(getPValue())
          != java.lang.Double.doubleToLongBits(
              other.getPValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasMetricControl()) {
        hash = (37 * hash) + METRIC_CONTROL_FIELD_NUMBER;
        hash = (53 * hash) + getMetricControl().hashCode();
      }
      if (hasMetricTreatment()) {
        hash = (37 * hash) + METRIC_TREATMENT_FIELD_NUMBER;
        hash = (53 * hash) + getMetricTreatment().hashCode();
      }
      hash = (37 * hash) + AVG_CONTROL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAvgControl()));
      hash = (37 * hash) + AVG_TREATMENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAvgTreatment()));
      hash = (37 * hash) + P_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPValue()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RecommendationOuterClass.Recommendation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecommendationOuterClass.Recommendation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RecommendationOuterClass.Recommendation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecommendationOuterClass.Recommendation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RecommendationOuterClass.Recommendation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Recommendation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Recommendation)
        RecommendationOuterClass.RecommendationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RecommendationOuterClass.internal_static_Recommendation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RecommendationOuterClass.internal_static_Recommendation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RecommendationOuterClass.Recommendation.class, RecommendationOuterClass.Recommendation.Builder.class);
      }

      // Construct using RecommendationOuterClass.Recommendation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        if (metricControlBuilder_ == null) {
          metricControl_ = null;
        } else {
          metricControl_ = null;
          metricControlBuilder_ = null;
        }
        if (metricTreatmentBuilder_ == null) {
          metricTreatment_ = null;
        } else {
          metricTreatment_ = null;
          metricTreatmentBuilder_ = null;
        }
        avgControl_ = 0D;

        avgTreatment_ = 0D;

        pValue_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RecommendationOuterClass.internal_static_Recommendation_descriptor;
      }

      @java.lang.Override
      public RecommendationOuterClass.Recommendation getDefaultInstanceForType() {
        return RecommendationOuterClass.Recommendation.getDefaultInstance();
      }

      @java.lang.Override
      public RecommendationOuterClass.Recommendation build() {
        RecommendationOuterClass.Recommendation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public RecommendationOuterClass.Recommendation buildPartial() {
        RecommendationOuterClass.Recommendation result = new RecommendationOuterClass.Recommendation(this);
        result.id_ = id_;
        if (metricControlBuilder_ == null) {
          result.metricControl_ = metricControl_;
        } else {
          result.metricControl_ = metricControlBuilder_.build();
        }
        if (metricTreatmentBuilder_ == null) {
          result.metricTreatment_ = metricTreatment_;
        } else {
          result.metricTreatment_ = metricTreatmentBuilder_.build();
        }
        result.avgControl_ = avgControl_;
        result.avgTreatment_ = avgTreatment_;
        result.pValue_ = pValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RecommendationOuterClass.Recommendation) {
          return mergeFrom((RecommendationOuterClass.Recommendation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RecommendationOuterClass.Recommendation other) {
        if (other == RecommendationOuterClass.Recommendation.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.hasMetricControl()) {
          mergeMetricControl(other.getMetricControl());
        }
        if (other.hasMetricTreatment()) {
          mergeMetricTreatment(other.getMetricTreatment());
        }
        if (other.getAvgControl() != 0D) {
          setAvgControl(other.getAvgControl());
        }
        if (other.getAvgTreatment() != 0D) {
          setAvgTreatment(other.getAvgTreatment());
        }
        if (other.getPValue() != 0D) {
          setPValue(other.getPValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RecommendationOuterClass.Recommendation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RecommendationOuterClass.Recommendation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private MetricOuterClass.Metric metricControl_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder> metricControlBuilder_;
      /**
       * <code>.Metric metric_control = 2;</code>
       * @return Whether the metricControl field is set.
       */
      public boolean hasMetricControl() {
        return metricControlBuilder_ != null || metricControl_ != null;
      }
      /**
       * <code>.Metric metric_control = 2;</code>
       * @return The metricControl.
       */
      public MetricOuterClass.Metric getMetricControl() {
        if (metricControlBuilder_ == null) {
          return metricControl_ == null ? MetricOuterClass.Metric.getDefaultInstance() : metricControl_;
        } else {
          return metricControlBuilder_.getMessage();
        }
      }
      /**
       * <code>.Metric metric_control = 2;</code>
       */
      public Builder setMetricControl(MetricOuterClass.Metric value) {
        if (metricControlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metricControl_ = value;
          onChanged();
        } else {
          metricControlBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Metric metric_control = 2;</code>
       */
      public Builder setMetricControl(
          MetricOuterClass.Metric.Builder builderForValue) {
        if (metricControlBuilder_ == null) {
          metricControl_ = builderForValue.build();
          onChanged();
        } else {
          metricControlBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Metric metric_control = 2;</code>
       */
      public Builder mergeMetricControl(MetricOuterClass.Metric value) {
        if (metricControlBuilder_ == null) {
          if (metricControl_ != null) {
            metricControl_ =
              MetricOuterClass.Metric.newBuilder(metricControl_).mergeFrom(value).buildPartial();
          } else {
            metricControl_ = value;
          }
          onChanged();
        } else {
          metricControlBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Metric metric_control = 2;</code>
       */
      public Builder clearMetricControl() {
        if (metricControlBuilder_ == null) {
          metricControl_ = null;
          onChanged();
        } else {
          metricControl_ = null;
          metricControlBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Metric metric_control = 2;</code>
       */
      public MetricOuterClass.Metric.Builder getMetricControlBuilder() {
        
        onChanged();
        return getMetricControlFieldBuilder().getBuilder();
      }
      /**
       * <code>.Metric metric_control = 2;</code>
       */
      public MetricOuterClass.MetricOrBuilder getMetricControlOrBuilder() {
        if (metricControlBuilder_ != null) {
          return metricControlBuilder_.getMessageOrBuilder();
        } else {
          return metricControl_ == null ?
              MetricOuterClass.Metric.getDefaultInstance() : metricControl_;
        }
      }
      /**
       * <code>.Metric metric_control = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder> 
          getMetricControlFieldBuilder() {
        if (metricControlBuilder_ == null) {
          metricControlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder>(
                  getMetricControl(),
                  getParentForChildren(),
                  isClean());
          metricControl_ = null;
        }
        return metricControlBuilder_;
      }

      private MetricOuterClass.Metric metricTreatment_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder> metricTreatmentBuilder_;
      /**
       * <code>.Metric metric_treatment = 3;</code>
       * @return Whether the metricTreatment field is set.
       */
      public boolean hasMetricTreatment() {
        return metricTreatmentBuilder_ != null || metricTreatment_ != null;
      }
      /**
       * <code>.Metric metric_treatment = 3;</code>
       * @return The metricTreatment.
       */
      public MetricOuterClass.Metric getMetricTreatment() {
        if (metricTreatmentBuilder_ == null) {
          return metricTreatment_ == null ? MetricOuterClass.Metric.getDefaultInstance() : metricTreatment_;
        } else {
          return metricTreatmentBuilder_.getMessage();
        }
      }
      /**
       * <code>.Metric metric_treatment = 3;</code>
       */
      public Builder setMetricTreatment(MetricOuterClass.Metric value) {
        if (metricTreatmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metricTreatment_ = value;
          onChanged();
        } else {
          metricTreatmentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Metric metric_treatment = 3;</code>
       */
      public Builder setMetricTreatment(
          MetricOuterClass.Metric.Builder builderForValue) {
        if (metricTreatmentBuilder_ == null) {
          metricTreatment_ = builderForValue.build();
          onChanged();
        } else {
          metricTreatmentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Metric metric_treatment = 3;</code>
       */
      public Builder mergeMetricTreatment(MetricOuterClass.Metric value) {
        if (metricTreatmentBuilder_ == null) {
          if (metricTreatment_ != null) {
            metricTreatment_ =
              MetricOuterClass.Metric.newBuilder(metricTreatment_).mergeFrom(value).buildPartial();
          } else {
            metricTreatment_ = value;
          }
          onChanged();
        } else {
          metricTreatmentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Metric metric_treatment = 3;</code>
       */
      public Builder clearMetricTreatment() {
        if (metricTreatmentBuilder_ == null) {
          metricTreatment_ = null;
          onChanged();
        } else {
          metricTreatment_ = null;
          metricTreatmentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Metric metric_treatment = 3;</code>
       */
      public MetricOuterClass.Metric.Builder getMetricTreatmentBuilder() {
        
        onChanged();
        return getMetricTreatmentFieldBuilder().getBuilder();
      }
      /**
       * <code>.Metric metric_treatment = 3;</code>
       */
      public MetricOuterClass.MetricOrBuilder getMetricTreatmentOrBuilder() {
        if (metricTreatmentBuilder_ != null) {
          return metricTreatmentBuilder_.getMessageOrBuilder();
        } else {
          return metricTreatment_ == null ?
              MetricOuterClass.Metric.getDefaultInstance() : metricTreatment_;
        }
      }
      /**
       * <code>.Metric metric_treatment = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder> 
          getMetricTreatmentFieldBuilder() {
        if (metricTreatmentBuilder_ == null) {
          metricTreatmentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MetricOuterClass.Metric, MetricOuterClass.Metric.Builder, MetricOuterClass.MetricOrBuilder>(
                  getMetricTreatment(),
                  getParentForChildren(),
                  isClean());
          metricTreatment_ = null;
        }
        return metricTreatmentBuilder_;
      }

      private double avgControl_ ;
      /**
       * <code>double avg_control = 4;</code>
       * @return The avgControl.
       */
      @java.lang.Override
      public double getAvgControl() {
        return avgControl_;
      }
      /**
       * <code>double avg_control = 4;</code>
       * @param value The avgControl to set.
       * @return This builder for chaining.
       */
      public Builder setAvgControl(double value) {
        
        avgControl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double avg_control = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvgControl() {
        
        avgControl_ = 0D;
        onChanged();
        return this;
      }

      private double avgTreatment_ ;
      /**
       * <code>double avg_treatment = 5;</code>
       * @return The avgTreatment.
       */
      @java.lang.Override
      public double getAvgTreatment() {
        return avgTreatment_;
      }
      /**
       * <code>double avg_treatment = 5;</code>
       * @param value The avgTreatment to set.
       * @return This builder for chaining.
       */
      public Builder setAvgTreatment(double value) {
        
        avgTreatment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double avg_treatment = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvgTreatment() {
        
        avgTreatment_ = 0D;
        onChanged();
        return this;
      }

      private double pValue_ ;
      /**
       * <code>double p_value = 6;</code>
       * @return The pValue.
       */
      @java.lang.Override
      public double getPValue() {
        return pValue_;
      }
      /**
       * <code>double p_value = 6;</code>
       * @param value The pValue to set.
       * @return This builder for chaining.
       */
      public Builder setPValue(double value) {
        
        pValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double p_value = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPValue() {
        
        pValue_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Recommendation)
    }

    // @@protoc_insertion_point(class_scope:Recommendation)
    private static final RecommendationOuterClass.Recommendation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecommendationOuterClass.Recommendation();
    }

    public static RecommendationOuterClass.Recommendation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Recommendation>
        PARSER = new com.google.protobuf.AbstractParser<Recommendation>() {
      @java.lang.Override
      public Recommendation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Recommendation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Recommendation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Recommendation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public RecommendationOuterClass.Recommendation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Recommendation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Recommendation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024Recommendation.proto\032\014Metric.proto\"\235\001\n" +
      "\016Recommendation\022\n\n\002id\030\001 \001(\t\022\037\n\016metric_co" +
      "ntrol\030\002 \001(\0132\007.Metric\022!\n\020metric_treatment" +
      "\030\003 \001(\0132\007.Metric\022\023\n\013avg_control\030\004 \001(\001\022\025\n\r" +
      "avg_treatment\030\005 \001(\001\022\017\n\007p_value\030\006 \001(\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MetricOuterClass.getDescriptor(),
        });
    internal_static_Recommendation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Recommendation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Recommendation_descriptor,
        new java.lang.String[] { "Id", "MetricControl", "MetricTreatment", "AvgControl", "AvgTreatment", "PValue", });
    MetricOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
